### ISSUE TITLE
No files matching the pattern 

### ISSUE THREAD

**Issue by gregorvoinov** [nuxt-community/stylelint-module#33]
Hi,

I get this error 

**StylelintError** friendly-errors 
> No files matching the pattern "C:\myProject\assets\**\*.{s?(a|c)ss,less,stylus}, C:\myProject\{components,layouts,pages}\**\*.vue" were found.

my dependencies

>  "dependencies": {
>     "nuxt": "^2.11.0",
>     "@nuxtjs/axios": "^5.9.3",
>     "@nuxtjs/pwa": "^3.0.0-0"
>   },
>   "devDependencies": {
>     "@nuxtjs/eslint-config": "^2.0.0",
>     "@nuxtjs/eslint-module": "^1.1.0",
>     "@nuxtjs/stylelint-module": "^3.2.0",
>     "@nuxtjs/tailwindcss": "^1.3.0",
>     "babel-eslint": "^10.0.3",
>     "eslint": "^6.8.0",
>     "eslint-config-prettier": "^4.1.0",
>     "eslint-plugin-nuxt": ">=0.5.0",
>     "eslint-plugin-prettier": "^3.1.2",
>     "glob-all": "^3.1.0",
>     "node-sass": "^4.13.0",
>     "prettier": "^1.16.4",
>     "purgecss-webpack-plugin": "^1.6.0",
>     "sass-loader": "^8.0.2",
>     "stylelint": "^13.0.0"
>   }

but there is a tailwind.css file inside assets\css\ folder and a lot of files inside my components,layouts,pages folders...

stylelint version 12.0.1 works

Is this a bug?

**Comment by ricardogobbosouza** [comment]
Hi @gregorvoinov 
Its a bug of [stylelint-webpack-plugin](https://github.com/webpack-contrib/) with the new version of `stylelint` hear a change in the `globby`. See https://github.com/stylelint/stylelint/pull/4254.

**Comment by ricardogobbosouza** [comment]
I'll fix it today

**Comment by ricardogobbosouza** [comment]
Fixed, try using the new version 3.2.1

**Comment by gregorvoinov** [comment]
works now ;)

**Comment by Amir-Mohamadi** [comment]
hi . 
sorry open agin , i created new nuxt project with stylelint-module.
when run nuxt get error :
`No files matching the pattern .../assets/**/*.{s?(a|c)ss,less,stylus}, .../{components,layouts,pages}/**/*.vue`
I created a sample scss file in assets folder but error was not resolved.
`
"nuxt": "^2.12.2",
"stylelint": "^13.3.0"
"@nuxtjs/stylelint-module": "^3.2.2",
`

**Comment by qmolab** [comment]
It is broken again...
